### ISSUE TITLE
'Open KLB' triggers exception

### ISSUE THREAD

**Issue by erjel** [bigdataviewer/bigdataviewer_fiji#13]
Hi,

I currently try to use the TGMM algorithms to my own data set (time series of single fluorescence channel volumes (X, Y, Z) ) following the "[Software_Guide_Compact](https://www.janelia.org/janelia-mouse-atlas)".

In the instructions, there is a part when the TGMM results are exported to xml/ hdf5 by the Fiji bigdataviewer plugin:

```
Import TGMM objects using MaMuT importer in Fiji. As image data location use
the .xml file generated from the .klb image files, as described in the first section
“Setting up the software environment”
```

According to the chapter _Setting up the software environment_ I have to use the plugin function `Open KLB`:

```
[...] to generate a new .xml file from a .klb image series in Fiji, follow
these steps:
 - Go to “Plugins”, “BigDataViewer”, and select “Open KLB”.
```

As soon as I press the button a Exception Window appears:

Exception Window Message:
```
(Fiji Is Just) ImageJ 2.0.0-rc-69/1.52p; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 364MB of 24450MB (1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/preibisch/mvrecon/fiji/spimdata/SpimData2
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:309)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:163)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/preibisch/mvrecon/fiji/spimdata/SpimData2
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:305)
	... 5 more
Caused by: java.lang.NoClassDefFoundError: net/preibisch/mvrecon/fiji/spimdata/SpimData2
	at org.janelia.simview.klb.bdv.ui.KlbIjPlugin.run(KlbIjPlugin.java:25)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.ClassNotFoundException: net.preibisch.mvrecon.fiji.spimdata.SpimData2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
```
Console Window Message:
```
[ERROR] Module threw error
java.lang.NoClassDefFoundError: net/preibisch/mvrecon/fiji/spimdata/SpimData2
	at org.janelia.simview.klb.bdv.ui.KlbIjPlugin.run(KlbIjPlugin.java:25)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.preibisch.mvrecon.fiji.spimdata.SpimData2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more

```

**Comment by tpietzsch** [comment]
@erjel Could you try to activate the BigStitcher update site in your Fiji? This should bring in the `net/preibisch/mvrecon/fiji/spimdata/SpimData2` that is not found, and maybe that solves the problem already.
(Fiji menu Help -> Update..., then "Manage Update Sites")
<img width="779" alt="Screenshot 2019-09-23 at 12 02 41" src="https://user-images.githubusercontent.com/622070/65417571-a2899980-ddfa-11e9-8a01-f2cdda52ea48.png">

**Comment by tpietzsch** [comment]
Can I close this?
